"""Provider-independent LLM client interface with graceful deterministic fallback."""
import os
from typing import Optional
from dotenv import load_dotenv

# Load from .env first; fallback to .env.example
load_dotenv()
load_dotenv(".env.example")

from ai.prompts import EXPLANATION_SYSTEM_PROMPT


class LLMClient:
    """
    Provider-agnostic interface for AI narrative generation.
    Supports Groq, Google Gemini, OpenAI, and a built-in deterministic fallback generator.
    """

    def __init__(self, provider: Optional[str] = None):
        # Reload env vars in case user updated them via UI or file
        load_dotenv(override=True)
        load_dotenv(".env.example")

        self.groq_key = os.getenv("GROQ_API_KEY", "").strip("\"'")
        self.gemini_key = os.getenv("GEMINI_API_KEY", "").strip("\"'")
        self.openai_key = os.getenv("OPENAI_API_KEY", "").strip("\"'")

        requested_provider = (provider or os.getenv("AI_PROVIDER", "")).lower()

        # If provider is not explicitly set, auto-detect based on available keys
        if not requested_provider or requested_provider == "mock":
            if self.groq_key:
                self.provider = "groq"
            elif self.gemini_key:
                self.provider = "gemini"
            elif self.openai_key:
                self.provider = "openai"
            else:
                self.provider = "mock"
        else:
            self.provider = requested_provider

    def generate_text(self, prompt: str, system_instruction: str = EXPLANATION_SYSTEM_PROMPT) -> str:
        """Dispatches prompt to configured provider or falls back to deterministic rule engine."""
        
        # 1. Groq Provider
        if self.provider == "groq" and self.groq_key:
            from groq import Groq
            groq_models = ["qwen/qwen3.8-27b", "openai/gpt-oss-120b", "llama-3.3-70b-versatile", "llama-3.1-8b-instant"]
            for model_id in groq_models:
                try:
                    client = Groq(api_key=self.groq_key)
                    completion = client.chat.completions.create(
                        model=model_id,
                        messages=[
                            {"role": "system", "content": system_instruction},
                            {"role": "user", "content": prompt},
                        ],
                        temperature=0.3,
                        max_tokens=1000,
                    )
                    content = completion.choices[0].message.content
                    if content:
                        return f"*(Generated by Groq • {model_id})*\n\n{content}"
                except Exception:
                    continue

        # 2. Google Gemini Provider
        if self.provider == "gemini" and self.gemini_key:
            from google import genai
            gemini_models = ["gemini-3.6-flash", "gemini-2.0-flash", "gemini-1.5-flash"]
            for model_id in gemini_models:
                try:
                    client = genai.Client(api_key=self.gemini_key)
                    response = client.models.generate_content(
                        model=model_id,
                        contents=prompt,
                        config={"system_instruction": system_instruction},
                    )
                    if response.text:
                        return f"*(Generated by Google Gemini • {model_id})*\n\n{response.text}"
                except Exception:
                    continue

        # 3. OpenAI Provider
        if self.provider == "openai" and self.openai_key:
            try:
                from openai import OpenAI
                client = OpenAI(api_key=self.openai_key)
                response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[
                        {"role": "system", "content": system_instruction},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.2,
                )
                content = response.choices[0].message.content
                if content:
                    return f"*(Generated by OpenAI • GPT-4o mini)*\n\n{content}"
            except Exception:
                pass

        # 4. Built-in offline fallback narrative
        return self._generate_fallback_narrative(prompt)

    def _generate_fallback_narrative(self, prompt: str) -> str:
        """Generates a professional deterministic analysis when no external LLM is configured."""
        if "Missing essential data points" in prompt or "Review the following client financial profile" in prompt:
            return (
                "### Fact-Find Completeness & Inconsistency Audit (Deterministic Rule Engine)\n\n"
                "**1. Essential Safety Buffer Audit:**\n"
                "- **Healthcare Reserve:** Ensure an explicit healthcare capital reserve (PKR 1.5M–3M) is earmarked to prevent medical shocks from eroding living capital.\n"
                "- **Emergency Reserve Runway:** Verify that liquid bank cash covers at least 6 months of essential living expenses before committing funds to long-term illiquid assets.\n\n"
                "**2. Potential Red Flags & Vulnerabilities:**\n"
                "- **Inflation Dependency:** Ensure projected retirement expenses are indexed to Pakistan's ongoing inflation cycles (recommended 8%–12% baseline assumption).\n"
                "- **Asset Concentration:** Illiquid real estate and family residences do not generate monthly retirement cash flow unless rented or liquidated.\n\n"
                "**3. Recommended Adviser Discussion Points:**\n"
                "- Review the timing and tax treatment of Provident Fund / Gratuity disbursements upon retirement.\n"
                "- Validate whether financial support for dependents will taper off or continue permanently."
            )

        return (
            "### AI Suitability & Sustainability Narrative (Deterministic Engine)\n\n"
            "**Executive Financial Summary:**\n"
            "This assessment evaluates retirement readiness and capital sustainability based strictly on verified cash-flow "
            "projections and actuarial assumptions. Net worth and investable capital were modeled against projected living costs, "
            "incorporating local inflation compounding in PKR.\n\n"
            "**Risk vs. Capacity Suitability Observation:**\n"
            "RetireWise AI evaluated the critical balance between psychological risk tolerance and objective financial capacity. "
            "In retirement planning, capacity for loss must strictly govern portfolio asset allocation. Even if a client exhibits "
            "comfort with market volatility, essential living expenses and dependent obligations limit the acceptable drawdown risk.\n\n"
            "**Strategic Adviser Guidance:**\n"
            "- Ensure liquid emergency reserves meet or exceed 6 months of essential living costs.\n"
            "- Prioritize capital preservation for baseline income needs, allocating growth assets only to surplus discretionary reserves.\n"
            "- Regularly stress-test against Pakistan's persistent double-digit inflation cycles and healthcare cost escalations."
        )
